FROM node:20-alpine

WORKDIR /app

COPY package.json .

RUN rm -rf node_modules package-lock.json /app/.cache && npm install

COPY . .

CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "7777"]