services:
  goderpad-backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: goderpad-backend
    volumes:
      - ./past:/app/past

  goderpad-nginx:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=${BACKEND_URL}
        - VITE_WS_URL=${WS_URL}
        - VITE_API_KEY=${API_KEY}
    depends_on:
      - goderpad-backend

networks:
  default:
    external:
      name: sce
