services:
  goderpad-redis:
    image: redis:7-alpine
    container_name: goderpad-redis
    ports:
      - "6379:6379"
    profiles:
      - code-execution

  goderpad-backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: goderpad-backend
    ports:
      - "7778:7778"
    environment:
      - REDIS_ADDR=goderpad-redis:6379
    volumes:
      - .:/app
      - /app/tmp

  goderpad-runner:
    build:
      context: .
      dockerfile: Dockerfile.runner
    container_name: goderpad-runner
    environment:
      - REDIS_ADDR=goderpad-redis:6379
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - goderpad-redis
    profiles:
      - code-execution

  goderpad-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: goderpad-frontend
    ports:
      - "7777:7777"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - goderpad-backend
    environment:
      - VITE_API_URL=http://localhost:7778
      - VITE_WS_URL=ws://localhost:7778

  goderpad-nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf
    depends_on:
      - goderpad-backend
      - goderpad-frontend
    ports:
      - 3001:80
