events {}

http {
    server {
        listen 80;

        location / {
            resolver 127.0.0.11 valid=15s;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_pass http://goderpad-frontend:7777;
        }

        location /api {
            resolver 127.0.0.11 valid=15s;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_pass http://goderpad-backend:7778;
            rewrite ^/api/(.*)$ /$1 break;
        }

        location /ws {
            resolver 127.0.0.11 valid=15s;
            proxy_set_header Host $host;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_pass http://goderpad-backend:7778;
        }

        location /health {
            access_log off;
            return 200 "healthy\n";
        }
    }
}
